### ISSUE TITLE
Performance drops when delay is introduced

### ISSUE THREAD

**Issue by dehmarc** [facebookincubator/mvfst#119] opened 2020-03-23 11:14 UTC
I have benchmarked the tperf performance of mvfst in mininet (and compared against tcp performance in iperf3). The results are shown in the images below. The duration was set to 60s.

I am wondering why the performance of mvfst drops significantly when a 10ms delay is present on the channel? Especially the quic_bbr performance is way superior to the tcp_bbr performance. It seems like a general bug since the throughput is bad for all congestion controls at 10ms delay even without losses.

The curves of quic_copa and quic_bbr stop at a loss of 3%, because then a "lossTimeoutExpired()"-error terminates the transmission. Would i need to manually cancel that timeout to prevent this error from occuring?

![bw100_delay0ms](https://user-images.githubusercontent.com/49490612/77310564-d2105480-6cfe-11ea-9801-3ac2b988cfb1.png)
![bw100_delay1ms](https://user-images.githubusercontent.com/49490612/77310568-d472ae80-6cfe-11ea-8839-f8cfa3f69de3.png)
![bw100_delay10ms](https://user-images.githubusercontent.com/49490612/77310578-d89ecc00-6cfe-11ea-82ea-1ad8c7c627b9.png)

**Comment by yangchi** [comment] 2020-03-23 16:09
You shouldn't have to cancel the timeout. That sounds like a bug.

**Comment by MischMetal** [comment] 2020-03-25 11:22
I'm facing similar issues. I tried modifying the `kMaxCwndInMss` parameter in QuicConstants.h (since tperf uses this to set a limit on its max cwnd), but it seems to have no effect. Here's a brief  summary of the throughputs for 30 sec `bbr` flows: 

Link speed (set with tc) | One-way delay | Throughput | `kMaxCwndInMss`
| --- | --- | --- | ---|
32 Mbps | 30 | 15 Mbps | 1666666
32 Mbps | 15 | 23.5 Mbps | 1666666
32 Mbps | 5 | 32 Mbps | 1666666
32 Mbps | 30 | 15 Mbps | 2000
32 Mbps | 15 | 23.5 Mbps | 2000
32 Mbps | 5 | 32 Mbps | 2000

This behaviour is consistent with other congestion controllers as well. My UDP recv windows are large enough, an iperf UDP flow is able to utilize the bandwidth. It looks like the cap is placed either by tperf or somewhere in the quic code, but I can't figure out where.

**Comment by dehmarc** [comment] 2020-03-25 13:27
I did further investigations. 
The throughput increases drastically as the window-parameter is changed (see plots below). Why does the initial window size of the stream have that much of an impact. Might be a bug?
![gso](https://user-images.githubusercontent.com/49490612/77541019-5d771a80-6ea4-11ea-9148-f7b644e63355.png)
![no_gso](https://user-images.githubusercontent.com/49490612/77541022-5ea84780-6ea4-11ea-88cb-fad1aefadba0.png)

Then i looked into the qlogger output. For some reason the cwnd does not scale when the default window is used. Does not look right to me either.
![current_cwnd](https://user-images.githubusercontent.com/49490612/77541237-ad55e180-6ea4-11ea-8e50-380ce7d742e9.png)

**Comment by MischMetal** [comment] 2020-03-25 16:13
Isn't the initial window size set in MSS? Did you increase the window size by increasing the number of packets in the initial window or did you just use a larger MSS?

**Comment by dehmarc** [comment] 2020-03-26 07:11
> Isn't the initial window size set in MSS? Did you increase the window size by increasing the number of packets in the initial window or did you just use a larger MSS?

I am talking about the tperf parameter "window" which corresponds to "Flow control window size". It is by default kDefaultStreamWindowSize = (64 + 1) * 1024

**Comment by yangchi** [comment] 2020-04-02 18:27
It's not a bug. You can't have more than a window amount of bytes inflight for a stream/conn (depending on if you are talking about stream window or conn window) before you get an window update from peer. So this is expected behavior.

Our default window is pretty small for perf testing purpose.

**Comment by yangchi** [comment] 2020-04-02 18:29
> Then i looked into the qlogger output. For some reason the cwnd does not scale when the default window is used. Does not look right to me either.


Was that with Cubic or BBR?

**Comment by dehmarc** [comment] 2020-04-07 15:50
> Was that with Cubic or BBR?

That was using BBR

**Comment by weiyuxingchen** [comment] 2020-04-10 07:45
@yangchi     I also encounter the problem of "losttimeoutexpired()", can you provide a solution to this problem.   Or, is this a bug and will you fix it.       @dehmarc  Is your problem solved？

I look forward to your reply！ Thank you very much.

**Comment by mjoras** [comment] 2020-04-10 15:32
@MischMetal  @dehmarc tperf and mvfst do not scale the flow control window automatically, so it is up to you to set it to some reasonable multiple of the BDP you are testing. Have you done that with the `--window` option on the client?

**Comment by mjoras** [comment] 2020-04-10 15:36
@dehmarc oh I see one of your plots is varying window. Note what I said above, this is the _flow control window_ not the initial congestion window. This is expected behavior. If a connection does not have connection flow control it will not be able to grow the congestion window.

I would recommend using a -window parameter of e.g. 2x BDP most of the time for testing.

**Comment by MischMetal** [comment] 2020-04-10 15:41
> @MischMetal @dehmarc tperf and mvfst do not scale the flow control window automatically, so it is up to you to set it to some reasonable multiple of the BDP you are testing. Have you done that with the `--window` option on the client?

Yes it did. Thanks! Can I know why mvfst uses such a small flow control window to start with?

**Comment by dehmarc** [comment] 2020-04-13 13:08
> @dehmarc oh I see one of your plots is varying window. Note what I said above, this is the _flow control window_ not the initial congestion window. This is expected behavior. If a connection does not have connection flow control it will not be able to grow the congestion window.
> 
> I would recommend using a -window parameter of e.g. 2x BDP most of the time for testing.

Thank you for your input. I did assume that it was some kind of wrong parameterization.

I set the window on the client-site to 2xBDP (1250000 Bytes). I further enabled gso and pacing. Other than that i used the default tperf settings.

Do you have any idea why the performance drops that much for mvfst when loss is introduced (see image below)?
![bbr](https://user-images.githubusercontent.com/49490612/79122548-37a0af80-7d98-11ea-8d37-14bdd861236f.png)

**Comment by mjoras** [comment] 2020-04-25 23:56
@dehmarc I don't know off the top of my head, no. Do you have a way I could reproduce one of the loss parameters on Linux?

**Comment by mjoras** [comment] 2020-04-26 00:37
@dehmarc I may have repro'd with tc. I am curious, if you increase the window to 3x BDP and you set this: https://github.com/facebookincubator/mvfst/blob/master/quic/state/TransportSettings.h#L24

to true, do you still see this?

**Comment by dehmarc** [comment] 2020-04-28 11:45
@mjoras  I have been using mininet for testing purposes.

I have tried to set largeProbeRttCwnd to true. It doesn't seem to have much of an impact (see image below). 
The increased window improves the performance though.

![bb2](https://user-images.githubusercontent.com/49490612/80483476-7321a900-8956-11ea-96ab-9c76230db746.png)

**Comment by mjoras** [comment] 2020-04-30 23:07
Interesting. For me with tc it made a large difference. The fact that the flow control is influencing it pretty significantly is strange.

@dehmarc  Can you share your mininet set up? It doesn't look like that would be hard for me to try, and it would make it easier to debug on our end.

**Comment by dehmarc** [comment] 2020-05-07 05:59
@mjoras I attached my basic mininet setup.
I slightly modified the tperf client to output the measured throughput to a json file.

To get the printed output from the client, you could use _h2.popen()_ instead of _h2.cmd()_ (_popen_ does not wait for the process to finish, you would need to ensure that. The server process must be manually killed when using _popen_).

[mininet_setup.zip](https://github.com/facebookincubator/mvfst/files/4590936/mininet_setup.zip)

**Comment by mjoras** [comment] 2020-05-08 22:31
@dehmarc thanks I will try to give this a try next week and see what I can find.

**Comment by dehmarc** [comment] 2020-06-08 06:01
> @dehmarc thanks I will try to give this a try next week and see what I can find.

Any updates?

**Comment by mjoras** [comment] 2020-06-22 03:27
@dehmarc not yet, though we have gotten another report that this seems to specifically happen with mvfst as the client, i.e. when someone has done similar tests with other QUIC implementations as the client, the problem does not occur.

I am going to look more into this issue in the next week, since if it's really a client side phenomenon there is very likely a bug outside of congestion control.

**Comment by mjoras** [comment] 2020-06-22 16:53
@dehmarc out of curiosity, could you try again with a very very large window? Something like 1073741824?

**Comment by mjoras** [comment] 2020-07-29 00:05
@dehmarc besides the flow control thing, I have a couple other suspects, it would be great if you could retest with a few things.

**Comment by dehmarc** [comment] 2020-07-29 10:04
@mjoras I'm happy to help with a test runs. I will retest with you suggestion of an increased window of 1073741824 Bytes over the weekend or next week. Just let me know what other parameter changes will improve the performance.

**Comment by dehmarc** [comment] 2020-08-11 09:31
@mjoras I increased the window to 1073741824. It looks much better now. What exactly is the window parameter used for? I thought it was the initial advertised window, but I guess it is also the maximum flow control window?


![lineplot_rtt_large_windwow](https://user-images.githubusercontent.com/49490612/89881684-1e810180-dbc6-11ea-8464-0ba06923a7cf.png)

**Comment by yangchi** [comment] 2021-07-13 15:57
Hey sorry we didn't answer your question sooner. Yes it's for both initial and max.
I'm going to close this issue since you saw the number became better after you changed window param. If you still have perf problem, please open new issues. Thank you!

**Closed by yangchi** 2021-07-13 15:57 UTC
