### ISSUE TITLE
Example echo server not detecting when client closes connection

### ISSUE THREAD

**Issue by pfeatherstone** [facebookincubator/mvfst#66] opened 2019-11-08 07:55 UTC
Is it expected behaviour for a connection accepted by the server to not detect when a client connection closes down?

**Comment by pfeatherstone** [comment] 2019-11-08 11:31
I've based this observation on the echo example. Also I noticed the server connections do eventually close down but the timeout is massive (30 seconds +). Is this a timeout issue?

**Comment by pfeatherstone** [comment] 2019-11-08 11:35
Do we have to use PingCallback and periodically send pings to keep track of when a connection closes down?

**Comment by yangchi** [comment] 2019-11-08 15:57
as long as client sends close frames it shouldn't be an expected behavior.
I think what's happening here is that we are simply not closing the client connection.
The server connection was likely closed by idle timeout which defaults to 60s.

**Comment by pfeatherstone** [comment] 2019-11-08 16:29
Does the client not send a packet to the server connection informing it it’s about to close ?

**Comment by pfeatherstone** [comment] 2019-11-08 21:34
I guess I’m forcefully closing the client (Ctrl + C). The difference with TCP is that the kernel still does some cleanup when you kill your client. That doesn’t necessarily happen when everything happens in Userspace. I guess some careful signal handlers will solve this

**Comment by theDogOfPavlov** [comment] 2022-04-12 06:26
Hi,

I can confirm this behaviour during the initial exchange.

**WHAT DO I SEE?**

When closing a connection during the initial phase the CONNECTION_CLOSE frame seems to be ignored.

**WHAT DO I EXPECT TO SEE?**

Connections should be closed.

**SUPPORTING DETAIL**

see attached packet capture.

**
[example.zip](https://github.com/facebookincubator/mvfst/files/8470085/example.zip)
**

**Comment by hanidamlaj** [comment] 2022-12-21 21:17
Hey, thanks for reporting the issue! I think this was fixed in 8b5774e14536ebf6aadb6b1232c70aea2ac34e4f – the sample echo client now supports closing the connection with `/close`. Please feel free to re-open if you'd like a follow-up on anything else!

**Closed by hanidamlaj** 2022-12-21 21:17 UTC
