### ISSUE TITLE
Errors while running CTest

### ISSUE THREAD

**Issue by z6833** [facebookincubator/mvfst#80] opened 2019-12-20 08:28 UTC
I've got error while using  **command** "make test" under the directory mvfst/_build/build/ . Part of tests get passed, but some not . And Finally, I get an error :
 Errors while running CTest
make: *** [test] 错误 8
============My environments like this:=======
Centos7.5, gcc7.3.0, cmake3.10.0
============Detail information for test results===
Running tests...
Test project /home/h3c/zhao/mvfst/_build/build
        Start   1: QuicTransportTest.WriteDataWithProbing
  1/1129 Test   #1: QuicTransportTest.WriteDataWithProbing ......................................***Failed    0.03 sec
        Start   2: QuicTransportTest.NotAppLimitedWithLoss
  2/1129 Test   #2: QuicTransportTest.NotAppLimitedWithLoss .....................................***Failed    0.01 sec
        Start   3: QuicTransportTest.NotAppLimitedWithNoWritableBytes
  3/1129 Test   #3: QuicTransportTest.NotAppLimitedWithNoWritableBytes ..........................***Failed    0.01 sec
...
1127 - StreamStateFunctionsTests.ResetOffsetGreaterThanStreamFlowControl (Failed)
1128 - StreamStateFunctionsTests.ResetOffsetGreaterThanConnFlowControl (Failed)
1129 - StreamStateFunctionsTests.ResetAfterReadingAllBytesTillFin (Failed)
Errors while running CTest
make: *** [test] 错误 8

======================================
And I have output the whole logs in the make_test.log
[make_test.log](https://github.com/facebookincubator/mvfst/files/3987397/make_test.log)
===========Anyone can help ? Thanks so much .=====

**Comment by yangchi** [comment] 2019-12-20 15:27
i just pulled master and ran the tests. Some of them failed with timeout errors. But i saw much fewer failures than your log showed. It will be more helpful if you can provide more information about the errors in the tests. Currently all it shows are just tests failed. Without a repro and without such info it's impossible to debug this.

**Comment by zhao6833** [comment] 2019-12-23 01:22
I pulled master and updated a .sh file  to indtall dependencies for centos7.5 . Path for dependencies : mvfst/third_parties/ ...
[test.zip](https://github.com/facebookincubator/mvfst/files/3993263/test.zip)
That's the all changes I have made . I just installed the dependencies into system env , not in mvfst/_build/deps. I do not know weather it affects or not .

**Comment by yangchi** [comment] 2019-12-23 17:05
Hmm.... Is that zip file your change & log? I'm realy not a big fan of downloading random files from internet to read logs since i have no idea what's in them. Can you just paste your changes and logs in some online paste tools? (github gist or pastebin.com both work fine for this purpose)

**Comment by yangchi** [comment] 2019-12-23 17:22
Meh. I opened the file anyway. It looks like the zip file only has build script changes. Can you run ctest with verbose output and share the output somewhere? Thanks

**Comment by yangchi** [comment] 2019-12-23 17:29
For example, in the $MVFST/_build/build dir, if you do `ctest -R WriteDataWithProbing -V`, then it will limit the test to anything that only matches WriteDataWithProbing in the testname and will print verbose output to your console. The verbose output for these failed tests are very useful for debugging here since we cannot repro the test failures.

**Comment by zhao6833** [comment] 2019-12-25 11:26
@yangchi   Thanks for your patient response . 
 I tried the commands `ctest -R WriteDataWithProbing -V `, and I got the logs :
[test.log](https://github.com/facebookincubator/mvfst/files/4000344/test.log) . I tried my best to solve the error, but it just did not work .  Could you give me any suggestion on this matter?

**Comment by zhao6833** [comment] 2019-12-25 13:08
@yangchi Oh, I've find the cause for the failing test . I reinstalled gflags with `-DBUILD_SHARED_LIBS=ON`, and I got 99% examples passed . Yes, there left one failed . And I got the log with `ctest -R WriteDataWithProbing`:
[test.log](https://github.com/facebookincubator/mvfst/files/4000464/test.log), and logs with commands `make test`:
[make_test.log](https://github.com/facebookincubator/mvfst/files/4000466/make_test.log)
emmmm...

**Comment by yangchi** [comment] 2019-12-26 15:53
Great! We are aware of the Takeover test being flaky. Glad you got the rest of them passed. InvalidConnection is flaky as well by the way. So you will see that one fail from time to time too. We will fix it but I really don't know when.

**Comment by yangchi** [comment] 2020-01-24 05:30
I think everything is fixed now. Feel free to reopen if you see new test failures. Thank you!

**Closed by yangchi** 2020-01-24 05:30 UTC

**Comment by zeng215217** [comment] 2022-10-20 22:48
如果您正在为支持实验性 Web 组件功能（如 SIMD 和 SSE2）的浏览器进行编译，请使用以下代码。
cmake -DCMAKE_TOOLCHAIN_FILE=../emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DNCNN_SIMPLEOMP=ON -DNCNN_BUILD_TESTS=ON ..
但是在使用使用 SIMD SSE2，使用NCNN的内置测试用例来检查编译是否成功。：
TESTS_EXECUTABLE_LOADER=node TESTS_EXECUTABLE_LOADER_ARGUMENTS="--experimental-wasm-simd;--experimental-wasm-threads;--experimental-wasm-bulk-memory" ctest --output-on-failure -j 2

下面就全部报错：（1-88全部报错，这里只列出一个）
88/88 Test #88: test_yolov3detectionoutput .......***Failed    0.01 sec
CMake Error at /home/zeng/ncnn2/ncnn/cmake/run_test.cmake:4 (message):
  Test failed with return value 'No such file or directory'

	 88 - test_yolov3detectionoutput (Failed)
Errors while running CTest
这是什么原因，我不明白，有人解答一下嘛
