### ISSUE TITLE
Unable to build on Ubuntu-16.04.6 LTS

### ISSUE THREAD

**Issue by hashkash** [facebookincubator/mvfst#151] opened 2020-08-04 09:39 UTC
Hey,

I'm unable to build on my Ubuntu system (VM) as well. Here's the output from the terminal. 

```
maybachufer@kreuzberg:~/QUIC/mvfst$ ./build_helper.sh
[ INFO ] Build dir is not set. So going to build into _build
+ detect_platform
++ uname -s
+ unameOut=Linux
+ case "${unameOut}" in
+ Platform=Linux
+ echo -e '\033[0;32mDetected platform: Linux \033[0m'
Detected platform: Linux
+ setup_fmt
+ FMT_DIR=/home/maybachufer/QUIC/mvfst/_build/deps/fmt
+ FMT_BUILD_DIR=/home/maybachufer/QUIC/mvfst/_build/deps/fmt/build/
+ '[' '!' -d /home/maybachufer/QUIC/mvfst/_build/deps/fmt ']'
+ cd /home/maybachufer/QUIC/mvfst/_build/deps/fmt
+ git fetch --tags
+ git checkout 6.2.1
HEAD is now at 19bd751... Update version
+ echo -e '\033[0;32mBuilding fmt \033[0m'
Building fmt
+ mkdir -p /home/maybachufer/QUIC/mvfst/_build/deps/fmt/build/
+ cd /home/maybachufer/QUIC/mvfst/_build/deps/fmt/build/
./build_helper.sh: line 180: CMAKE_EXTRA_ARGS[@]: unbound variable
```

And then, if I try to run the getdeps script, this is what I get.

```
maybachufer@kreuzberg:~/QUIC/mvfst$ ./getdeps.sh
+ TOOLCHAIN_DIR=/opt/rh/devtoolset-8/root/usr/bin
+ [[ -d /opt/rh/devtoolset-8/root/usr/bin ]]
++ dirname ./getdeps.sh
+ PROJECT_DIR=.
+ GETDEPS_PATHS=("$PROJECT_DIR/build/fbcode_builder/getdeps.py" "$PROJECT_DIR/../../opensource/fbcode_builder/getdeps.py")
++ pwd
+ ROOT_DIR=/home/maybachufer/QUIC/mvfst
+ STAGE=/home/maybachufer/QUIC/mvfst/_build/
+ mkdir -p /home/maybachufer/QUIC/mvfst/_build/
+ for getdeps in '"${GETDEPS_PATHS[@]}"'
+ [[ -x ./build/fbcode_builder/getdeps.py ]]
+ ./build/fbcode_builder/getdeps.py build mvfst --current-project mvfst --install-prefix=/home/maybachufer/QUIC/mvfst/_build/
  File "./build/fbcode_builder/getdeps.py", line 545
    f"Will reconfigure cmake because {dep_file} is newer than {built_marker}"
                                                                            ^
SyntaxError: invalid syntax
```

I'm on a Linux 4.4.0-142-generic kernel. I had tried this on my macOS Catalina yesterday and hit the same CMAKE issue from the build_helper script. Would be super grateful if someone could help me out here.

Thanks,
Kash

**Comment by lnicco** [comment] 2020-08-05 17:25
thanks for reporting, the CMAKE_EXTRA_ARGS error is something I have also run into. I'll take a look at how to fix it. 

For getdeps.sh, looks like python3 is required

**Comment by lnicco** [comment] 2020-08-06 15:10
Duplicate of #143

**Closed by lnicco** 2020-08-06 15:10 UTC
