### ISSUE TITLE
lossTimeOut Expired problem

### ISSUE THREAD

**Issue by Enjia** [facebookincubator/mvfst#121] opened 2020-04-02 06:28 UTC
Hi, when I run tperf with certain conditions that delay=40ms and loss=1%/3%/5%/10% using linux tc command, server breaks down after seconds of transferring with message "error=LocalError, no error, lossTimeOut Expired() error". However when there's no such limitation in delay and loss or just set delay time, the whole program runs well. So have you tested tperf in shuch network conditions with different composition of delay and loss? Thanks!

**Comment by yangchi** [comment] 2020-04-02 18:28
I think this might be a 3rd report of such. #119 mentioned this. And there mighe have been another issue opened by you in the past mentioned the samething iirc.

We do test tperf with such condtions in TC, though we have never tested with loss > 3%

**Comment by lnicco** [comment] 2020-04-05 01:16
Duplicate of #119

**Closed** 2020-04-05 01:16 UTC
